// lib/utils/constants.dart

// List of nationalities
const List<String> nationalityList = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguans',
  'Argentinean',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Barbudans',
  'Batswana',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comoran',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djibouti',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorean',
  'Egyptian',
  'Emirian',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinea-Bissauan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Herzegovinian',
  'Honduran',
  'Hungarian',
  'I-Kiribati',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittian and Nevisian',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Liechtensteiner',
  'Lithuanian',
  'Luxembourger',
  'Macedonian',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivan',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Moroccan',
  'Mosotho',
  'Motswana',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Ni-Vanuatu',
  'Nicaraguan',
  'Nigerien',
  'North Korean',
  'Northern Irish',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'San Marinese',
  'Sao Tomean',
  'Saudi',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovakian',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamer',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian or Tobagonian',
  'Tunisian',
  'Turkish',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbekistani',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemenite',
  'Zambian',
  'Zimbabwean'
];


// List of visa statuses
const List<String> visaStatusList = [
  'Diplomat',
  'Official',
  'Professor',
  'Artist',
  'Religious Activities',
  'Journalist',
  'Investor/Business Manager',
  'Legal/Accounting Services',
  'Medical Services',
  'Researcher',
  'Instructor',
  'Engineer/Specialist in Humanities/International Services',
  'Intra-company Transferee',
  'Nursing Care',
  'Entertainer',
  'Skilled Labor',
  'Technical Intern Training',
  'Cultural Activities',
  'Student',
  'Trainee',
  'Dependent',
  'Designated Activities',
  'Temporary Visitor',
  'Spouse or Child of Japanese National',
  'Spouse or Child of Permanent Resident',
  'Long-term Resident',
  'Permanent Resident'
];


// List of prefectures
const List<String> prefectureList = [
  "Hokkaido",
  "Aomori",
  "Iwate",
  "Miyagi",
  "Akita",
  "Yamagata",
  "Fukushima",
  "Ibaraki",
  "Tochigi",
  "Gunma",
  "Saitama",
  "Chiba",
  "Tokyo",
  "Kanagawa",
  "Niigata",
  "Toyama",
  "Ishikawa",
  "Fukui",
  "Yamanashi",
  "Nagano",
  "Gifu",
  "Shizuoka",
  "Aichi",
  "Mie",
  "Shiga",
  "Kyoto",
  "Osaka",
  "Hyogo",
  "Nara",
  "Wakayama",
  "Tottori",
  "Shimane",
  "Okayama",
  "Hiroshima",
  "Yamaguchi",
  "Tokushima",
  "Kagawa",
  "Ehime",
  "Kochi",
  "Fukuoka",
  "Saga",
  "Nagasaki",
  "Kumamoto",
  "Oita",
  "Miyazaki",
  "Kagoshima",
  "Okinawa"
];


// List of Japanese proficiency levels
const List<String> proficiencyList = [
  'JLPT N5 (Beginner)',
  'JLPT N4 (Elementary)',
  'JLPT N3 (Intermediate)',
  'JLPT N2 (Pre-advanced)',
  'JLPT N1 (Advanced)',
];

// Map of prefectures to their wards
const Map<String, List<String>> wardsMap = {
"Hokkaido": ["Atsubetsu", "Chūō", "Higashi", "Kita", "Kiyota", "Minami", "Nishi", "Shiroishi", "Teine", "Toyohira"],
    "Aomori": [],
    "Iwate": [],
    "Miyagi": ["Aoba", "Izumi", "Miyagino", "Taihaku", "Wakabayashi"],
    "Akita": [],
    "Yamagata": [],
    "Fukushima": [],
    "Ibaraki": [],
    "Tochigi": [],
    "Gunma": [],
    "Saitama": ["Chūō", "Iwatsuki", "Kita", "Midori", "Minami", "Minuma", "Nishi", "Omiya", "Sakura", "Urawa"],
    "Chiba": ["Chūō", "Hanamigawa", "Inage", "Midori", "Mihama", "Wakaba"],
    "Tokyo": ["Adachi", "Arakawa", "Bunkyō", "Chiyoda", "Chūō", "Edogawa", "Itabashi", "Katsushika", "Kita", "Kōtō", "Meguro", "Minato", "Nakano", "Nerima", "Ōta", "Setagaya", "Shibuya", "Shinagawa", "Shinjuku", "Suginami", "Sumida", "Toshima", "Taitō"],
    "Kanagawa": ["Aoba", "Asahi", "Hodogaya", "Isogo", "Izumi", "Kanagawa", "Kanazawa", "Kōhoku", "Kōnan", "Midori", "Minami", "Naka", "Nishi", "Sakae", "Seya", "Totsuka", "Tsurumi", "Tsuzuki", "Asao", "Kawasaki", "Miyamae", "Nakahara", "Saiwai", "Takatsu", "Tama"],
    "Niigata": ["Akiha", "Chūō", "Higashi", "Kita", "Kōnan", "Minami", "Nishi", "Nishikan"],
    "Toyama": [],
    "Ishikawa": [],
    "Fukui": [],
    "Yamanashi": [],
    "Nagano": [],
    "Gifu": [],
    "Shizuoka": ["Aoi", "Shimizu", "Suruga", "Chūō", "Hamana", "Tenryū"],
    "Aichi": ["Atsuta", "Chikusa", "Higashi", "Kita", "Meitō", "Midori", "Minami", "Minato", "Mizuho", "Moriyama", "Naka", "Nakagawa", "Nakamura", "Nishi", "Shōwa", "Tenpaku"],
    "Mie": [],
    "Shiga": [],
    "Kyoto": ["Fushimi", "Higashiyama", "Kamigyō", "Kita", "Minami", "Nakagyō", "Nishikyō", "Sakyō", "Shimogyō", "Ukyō", "Yamashina"],
    "Osaka": ["Abeno", "Asahi", "Chūō", "Fukushima", "Higashinari", "Higashisumiyoshi", "Higashiyodogawa", "Hirano", "Ikuno", "Joto", "Kita", "Konohana", "Minato", "Miyakojima", "Naniwa", "Nishi", "Nishinari", "Nishiyodogawa", "Suminoe", "Sumiyoshi", "Taishō", "Tennōji", "Tsurumi", "Yodogawa"],
    "Hyogo": ["Chūō", "Higashinada", "Hyōgo", "Kita", "Nada", "Nagata", "Nishi", "Suma", "Tarumi"],
    "Nara": [],
    "Wakayama": [],
    "Tottori": [],
    "Shimane": [],
    "Okayama": ["Higashi", "Kita", "Minami", "Naka"],
    "Hiroshima": ["Aki", "Asakita", "Asaminami", "Higashi", "Minami", "Naka", "Nishi", "Saeki"],
    "Yamaguchi": [],
    "Tokushima": [],
    "Kagawa": [],
    "Ehime": [],
    "Kochi": [],
    "Fukuoka": ["Chūō", "Hakata", "Higashi", "Jōnan", "Minami", "Sawara", "Nishi", "Kokurakita", "Kokuraminami", "Moji", "Tobata", "Wakamatsu", "Yahatahigashi", "Yahatanishi"],
    "Saga": [],
    "Nagasaki": [],
    "Kumamoto": ["Chūō", "Higashi", "Kita", "Minami", "Nishi"],
    "Oita": [],
    "Miyazaki": ["Chūō", "Midori", "Minami"],
    "Kagoshima": [],
    "Okinawa": []
};